version 0.2


phases:
  install: 
    commands: 
    - npm install
    - curl -sL https://deb.nodesource.com/setup_12.x | -E bash -
    - apt-get install -y nodejs
    - echo installing yarn 
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  pre_build:
    commands:
    - echo Installing dependencies...
    - yarn
  build:
    commands:
    - echo testing...
    - echo building...
    - yarn building
artifacts:
  files: 
    - "**/*"
    discard-paths: no
    base-directory: dist
